spring.application.name=ResumeIQ

server.port=8080


# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/resumeiq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

spring.datasource.username=root

spring.datasource.password=root


# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB


# ===============================
# OLLAMA
# ===============================

ollama.base-url=http://localhost:11434

ollama.model=qwen3:8b


# ===============================
# JWT
# ===============================

jwt.secret=resumeiq-development-secret-key-2026-change-this-before-production-98765432101234567890

jwt.expiration-ms=86400000